var routes4 = [ ];
/*
//Nabadwip To Asansol & Asansol To Nabadwip via Satgachia
"Taraknath Nabadwip to Asansol 0035: Nabadwip to Asansol [via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Andal More, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep.  – 4.20 am, Satgachia Dep. – 5.40 am, Barddhaman Dep. – 6.55 am, Durgapur City Center Dep. – 8.20 am, Asansol Arr. – 9.20 am,: ",
"Taraknath Nabadwip to Asansol 0035: Asansol To Nabadwip [via: Asansol, Kalipahari More, Raniganj Punjabi More, Andal More, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 10.00 am, Durgapur City Center Dep. – 11.10 pm, Barddhaman Dep. – 1.10 pm, Satgachia Dep. – 2.40 pm, Nabadwip Arr. – 3.45 pm,: ",

"Sweety Nabadwip to Asansol 1460: Nabadwip to Asansol [via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Andal More, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep.  – 5.05 am, Dhatrigram Dep. – 5.50 am Satgachia Dep. – 6.20 am, Barddhaman Dep. – 7.25 am, Panagarh Dep. – 8.15 am, Durgapur City Center Dep. – 8.50 am, Asansol Arr. – 9.50 am,: ",
"Sweety Nabadwip to Asansol 1460: Asansol To Nabadwip [via: Asansol, Kalipahari More, Raniganj Punjabi More, Andal More, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 11.40 am, Durgapur City Center Dep. – 1.00 pm, Panagarh Dep. – 1.30 pm, Barddhaman Dep. – 2.40 pm, Satgachia Dep. – 4.00 pm, Dhatrigram Dep. – 4.35 pm, Nabadwip Arr. – 5.15 pm,: ",

"Sweety Nabadwip to Asansol 9888: Nabadwip to Asansol [via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Andal More, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep. – 5.40 am, Satgachia Dep.  – 7.05 am, Barddhaman Dep. – 8.30 am, Durgapur City Center Dep. – 10.00 am, Asansol Arr. – 11.00 am,: ",
"Sweety Nabadwip to Asansol 9888: Asansol To Nabadwip [via: Asansol, Kalipahari More, Raniganj Punjabi More, Andal More, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 1.20 pm, Durgapur City Center Dep. – 2.25 pm, Barddhaman Dep. – 4.20 pm, Satgachia Dep. – 5.30 pm, Nabadwip Arr. – 6.50 pm,: ",

//Nabadwip To Asansol & Asansol To Nabadwip via Kusumgram
"Chaitanya Nabadwip to Asansol 9662:Nabadwip to Asansol [via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Andal More, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep. – 4.00 am, Kusumgram Dep. – 5.20 am, Barddhaman Dep. – 6.30 am, Panagarh Dep. – 7.30 am, Durgapur City Center Dep. – 7.55 am, Asansol Arr. – 9.00 am,: ",
"Chaitanya Nabadwip to Asansol 9662:Asansol To Nabadwip [via: Asansol, Kalipahari More , Raniganj Punjabi More, Andal More, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 11.00 am, Durgapur City Center Dep. – 12.10 pm, Panagarh Dep. – 12.40 pm, Barddhaman Dep. – 2.15 pm, Kusumgram Dep. – 3.35 pm, Nabadwip Arr. – 4.30 pm,: ",

"Sweety Nabadwip to Asansol 5929: Nabadwip to Asansol [via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Andal More, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep. – 4.40 am, Kusumgram Dep. – 5.35 am, Barddhaman Dep. – 6.45 am, Budbud Dep. – 7.25 am, Panagarh Dep. – 7.40 am, Durgapur City Center Dep. – 8.10 am, Asansol Arr. – 9.10 am,: ",
"Sweety Nabadwip to Asansol 5929: Asansol To Nabadwip [via: Asansol, Kalipahari More , Raniganj Punjabi More, Andal More, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 9.50 am, Durgapur City Center Dep. – 10.50 am, Panagarh Dep. – 11.20 am, Budbud Dep. – 11.40 am, Barddhaman Dep. – 12.40 pm, Kusumgram Dep. – 2.00 pm, Nabadwip Arr. – 2.50 pm,: ",

"Ravi Nabadwip to Asansol 5161:Nabadwip to Asansol [via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Andal More, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep. – 5.15 am, Kusumgram Dep. – 6.25 am, Barddhaman Dep. – 7.55 am, Panagarh Dep. – 8.50 am, Durgapur City Center Dep. – 9.20 am, Asansol Arr. – 10.20 am,: ",
"Ravi Nabadwip to Asansol 5161:Asansol To Nabadwip [via: Asansol, Kalipahari More, Raniganj Punjabi More, Andal More, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 12.30 pm, Durgapur City Center Dep. – 1.35 pm, Panagarh Dep. – 2.00 pm, Barddhaman Dep. – 3.40 pm, Kusumgram Dep. – 5.15 pm, Nabadwip Arr. – 6.15 pm,: ",

"Krishna Nabadwip to Asansol 4681:Asansol To Nabadwip [via: Asansol, Kalipahari More, Raniganj Punjabi More, Andal More, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 6.30 am, Durgapur City Center Dep. – 7.30 am, Panagarh Dep. – 8.00 am, Barddhaman Arr. – 9.00 am, Barddhaman Dep. – 9.30 am, Kusumgram Dep. – 10.50 am, Nabadwip Arr. – 11.40 am,: ",
"Krishna Nabadwip to Asansol 4681:Nabadwip to Asansol [via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Andal More, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep. – 12.25 pm, Kusumgram Dep. – 1.35 pm, Barddhaman Dep. – 3.10 pm, Panagarh Dep. – 4.00 pm, Durgapur City Center Dep. – 4.25 pm, Asansol Arr. – 5.30 pm,: ",

"Chiranjit Nabadwip to Asansol 8115:Asansol To Nabadwip [via: Asansol, Kalipahari More , Raniganj Punjabi More, Andal More, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 5.15 am, Durgapur City Center Dep. – 6.20 am, Barddhaman Dep. – 8.05 am, Kusumgram Dep. – 9.30 am, Nabadwip Arr. – 10.25 am,: ",
"Chiranjit Nabadwip to Asansol 8115:Nabadwip to Asansol [via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Andal More, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep. – 12.00 pm, Kusumgram Dep. – 1.10 pm, Barddhaman Dep. – 2.40 pm, Durgapur City Center Dep. – 4.05 pm, Asansol Arr. – 5.10 pm,: ",
	
//Nabadwip To Benachity & Benachity To Nabadwip via Barddhaman
"Sanju Nabadwip to Benachity 7702:Nabadwip to Benachity [via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Benachity] : Nabadwip Dep. – 6.20 am, Kusumgram Dep. – 7.35 am, Barddhaman Dep. – 9.20 am, Durgapur City Center Dep. – 11.00 am, Benachity Arr. – 11.15 am,: ",
"Sanju Nabadwip to Benachity 7702: Benachity To Nabadwip [via: Benachity, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip] : Benachity Dep. – 2.10 pm, Durgapur City Center Dep. – 2.30 pm, Barddhaman Dep. – 4.30 pm, Kusumgram Dep. – 6.00 pm, Nabadwip Arr. – 7.00 pm,: ",

"Sanju Nabadwip to Benachity 7009:Nabadwip to Benachity [via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Benachity] : Nabadwip Dep. – 6.235 am, Kusumgram Dep. – 7.45 am, Barddhaman Dep. – 9.30 am, Durgapur City Center Dep. – 11.10 am, Benachity Arr. – 11.25 am,: ",
"Sanju Nabadwip to Benachity 7009: Benachity To Nabadwip [via: Benachity, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip] : Benachity Dep. – 3.20 pm, Durgapur City Center Dep. – 3.40 pm, Barddhaman Dep. – 5.45 pm, Kusumgram Dep. – 7.25 pm, Nabadwip Arr. – 8.20 pm,: ",

"Priyangshu Nabadwip to Benachity 1199: Benachity To Nabadwip [via: Benachity, Durgapur City Centre, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip] : Benachity Dep. – 6.40 am, Durgapur City Center Dep. – 6.55 am, Panagarh Dep. – 7.20 am, Barddhaman Dep. – 9.10 am, Kusumgram Dep. – 10.40 am, Nabadwip Arr. – 11.30 am,: ",
"Priyangshu Nabadwip to Benachity 1199: Nabadwip to Benachity [via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur City Centre, Benachity] : Nabadwip Dep. – 1.10 pm, Kusumgram Dep. – 2.20 pm, Barddhaman Dep. – 3.55 pm, Durgapur City Center Dep. – 5.35 pm, Benachity Arr. – 5.50 pm,: ",

//Nabadwip To Benachity & Benachity To Nabadwip via Katwa
"Dol Nabadwip to Benachity 4552: Nabadwip to Benachity [via: Nabadwip, Hematpur More, Shrirampur More, Parulia Bazar, Chhatni, Dainhat More, Katwa, Shrikhandaa, Kaichar, Nigan, Bolgona, Muratipur, Debpur, Guskara, Abhirmapur, Mankar, Budbud, Panagarh, Muchipara, Durgapur City Centre, Benachity] : Nabadwip Dep. – 5.20 am, Katwa Dep. – 6.40 am, Guskara Dep. – 8.20 am, Durgapur City Center Dep. – 10.00 am, Benachity Arr. – 10.15 am,: ",
"Dol Nabadwip to Benachity 4552: Benachity To Nabadwip [via: Benachity, Durgapur City Centre, Muchipara, Panagarh, Budbud, Mankar, Abhirampur, Guskara, Debpur, Muratipur, Bolgona, Nigan, Kaichar, Shrikhanda, Katwa, Dainhat More, Chhatni, Parulia Bazar, Shrirampur, Hematpur More, Nabadwi ] : Benachity Dep. – 10.40 am, Durgapur City Center Dep. – 10.55 am, Guskara Dep. – 12.45 pm, Katwa Dep. – 2.30 pm, Nabadwip Arr. – 3.45 pm,: ",

"Abhishek Nabadwip to Benachity 5258: Benachity To Nabadwip [via: Benachity, Durgapur City Centre, Muchipara, Panagarh, Budbud, Mankar, Abhirampur, Guskara, Debpur, Muratipur, Bolgona, Nigan, Kaichar, Shrikhanda, Katwa, Dainhat More, Chhatni, Purbasthali, Parulia Bazar, Shrirampur, Hematpur More, Nabadwip] : Budbud Dep. – 5.00 am, Guskara Dep. – 6.05 am, Bolgona Dep. – 7.05 am, Katwa Dep. – 7.55 am, Nabadwip Arr. – 9.30 am,: ",
"Abhishek Nabadwip to Benachity 5258: Nabadwip to Benachity [via: Nabadwip, Hematpur More, Shrirampur More, Parulia Bazar, Purbasthali, Chhatni, Dainhat More, Katwa, Shrikhandaa, Kaichar, Nigan, Bolgona, Muratipur, Debpur, Guskara, Abhirmapur, Mankar, Budbud, Panagarh, Muchipara, Durgapur City Centre, Benachity] : Nabadwip Dep. – 11.05 am, Katwa Dep. – 12.40 pm, Bolgona Dep. – 1.40 pm,  Guskara Dep. – 2.20 pm, Durgapur City Center Dep. – 4.05 pm, Benachity Arr. – 4.20 pm, Benachity Dep.- 6.05 pm, Durgapur City Center Dep. – 6.25 pm: ",

"Abhishek Nabadwip to Benachity 9349: Benachity To Nabadwip [via: Benachity, Durgapur City Centre, Muchipara, Panagarh, Budbud, Mankar, Abhirampur, Guskara, Debpur, Muratipur, Bolgona, Nigan, Kaichar, Shrikhanda, Katwa, Dainhat More, Chhatni, Purbasthali, Parulia Bazar, Shrirampur, Hematpur More, Nabadwip] : Benachity Dep. – 6.00 am, Durgapur City Center Dep. – 6.15 am Guskara Dep. – 8.00 am, Bolgona Dep. – 8.40 am, Katwa Dep. – 9.40 am, Nabadwip Arr. – 11.00 am,: ",
"Abhishek Nabadwip to Benachity 9349: Nabadwip to Benachity [via: Nabadwip, Hematpur More, Shrirampur More, Parulia Bazar, Purbasthali, Chhatni, Dainhat More, Katwa, Shrikhandaa, Kaichar, Nigan, Bolgona, Muratipur, Debpur, Guskara, Abhirmapur, Mankar, Budbud, Panagarh, Muchipara, Durgapur City Centre, Benachity] : Nabadwip Dep. – 12.20 pm, Katwa Dep. – 1.55 pm, Bolgona Dep. – 3.00 pm,  Guskara Dep. – 3.50 pm, Durgapur City Center Dep. – 5.45 pm, Benachity Arr. – 6.00 pm: ",
	

//Nabadwip To Bankura & Bankura To Nabadwip	
"Sweety Nabadwip to Bankura 4545: Nabadwip to Bankura [via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur Station, Borjora, Beliatore, Bankura] : Nabadwip Dep.  – 2.55 am, Dhatrigram Dep. – 3.30 am Satgachia Dep.  – 4.05 am, Barddhaman Dep. – 5.20 am, Durgapur Station Dep. – 6.55 am,: ",
"Sweety Nabadwip to Bankura 4545: Bankura To Nabadwip [via: Bankura, Beliatore , Borjora, Durgapur Station, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Bankura Dep. – 9.50 am, Durgapur Station Dep. – 11.30 am, Barddhaman Dep. – 1.45 pm, Satgachia Dep. – 2.50 pm, Dhatrigram Dep. – 3.20 pm,: ", 

"Sweety Nabadwip to Bankura 9311:Nabadwip to Bankura [via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur Station, Borjora, Beliatore, Bankura] : Nabadwip Dep. - 3.50 am, Barddhaman Dep. – 6.25 am Muchipara Dep. – 7.45 am, Durgapur Station Dep. – 8.10 am, Bankura Arr. – 9.30 am,: ",
"Sweety Nabadwip to Bankura 9311:Bankura To Nabadwip [via: Bankura, Beliatore , Borjora, Durgapur Station, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Bankura Dep. – 10.55 am, Durgapur Station Dep. – 12.20 am, Muchipara Dep. – 12.40 pm,  Barddhaman Dep. – 2.20 pm, Nabadwip Arr. – 4.50 pm : ",

"Sweety Nabadwip to Bankura 8207:Bankura To Nabadwip [via: Bankura, Beliatore , Borjora, Durgapur Station, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Bankura Dep. – 9.10 am, Durgapur Station Dep. – 10.45 am, Muchipara Dep. – 10.55 am,  Barddhaman Dep. – 12.20 pm, Satgachia Dep.- 1.45 pm, Dhatrigram Dep.- 2.10 pm, Nabadwip Arr. – 2.45 pm : ",
"Sweety Nabadwip to Bankura 8207:Nabadwip to Bankura [via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur Station, Borjora, Beliatore, Bankura] : Nabadwip Dep. - 3.50 pm, Dhatrigram Dep.- 4.35 pm, Satgachia Dep.- 5.10 pm, Barddhaman Dep. – 6.20 pm Muchipara Dep. – 7.50 pm, Durgapur Station Dep. – 8.40 pm, Bankura Arr. – 10.00 pm,: ",

"Dulhan Nabadwip to Bankura 1492:Bankura To Nabadwip [via: Bankura, Beliatore , Borjora, Durgapur Station, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Bankura Dep. – 4.10 am, Durgapur Station Dep. – 5.45 am, Muchipara Dep. – 5.55 am, Panagarh Dep.- 6.15 am,  Barddhaman Dep. – 7.25 am, Satgachia Dep.- 9.00 am, Dhatrigram Dep.- 9.30 am, Nabadwip Arr. – 10.00 am : ",
"Dulhan Nabadwip to Bankura 1492:Nabadwip to Bankura [via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur Station, Borjora, Beliatore, Bankura] : Nabadwip Dep. – 10.55 am, Dhatrigram Dep.- 11.40 am, Satgachia Dep.- 12.20 pm, Barddhaman Dep. – 1.35 pm, Panagarh Dep.- 2.35 pm, Muchipara Dep. – 2.50 pm, Durgapur Station Dep. – 3.15 pm, Bankura Arr. – 4.45 pm,: ",

//Nabadwip To Tarapith & Tarapith To Nabadwip
"Raju Nabadwip to Tarapith 1165:Nabadwip to Tarapith [via: Nabadwip, Hematpur More, Shrirampur More, Parulia Bazar, Purbasthali, Chhatni, Dainhat More, Katwa, Ketugram, Pachundi, Nirol, Komarpur, Kandra, Futisanko, Kirnahar, Labhpur, Chouhatta, Ahmadpur, Purandapur, Suri, Mohammad Bazar, Rampurhat, Tarapith] : Nabadwip Dep. – 4.40 am, Katwa Dep.- 6.10 am, Kirnahar Dep.- 7.40 am, Labhpur Dep. – 8.10 am, Ahmadpur Dep.- 8.40 am, Suri Dep. – 9.20 am, Mohammad Bazar Dep. – 9.45 am, Rampurhat Dep.- 10.10 am, Tarapith Arr. – 10.50 am,: ",
"Raju Nabadwip to Tarapith 1165:Tarapith to Nabadwip [via: Tarapith, Rampurhat, Mohammad Bazar, Suri, Purandapur, Ahmadpur, Chouhatta, Labhpur, Kirnahar, Futisanko, Kandra, Komarpur, Nirol, Pachundi, Ketugram, Katwa, Dainhat More, Chhatni, Purbasthali, Parulia Bazar, Shrirampur More, Hematpur More, Nabadwip] : Tarapith Dep. – 12.00 pm, Rampurhat Dep.- 12.40 pm, Mohammad Bazar Dep. – 1.30 pm, Suri Dep. – 2.00 pm, Ahmadpur Dep.- 2.45 pm, Labhpur Dep. – 3.20 pm, Kirnahar Dep.- 3.50 pm, Katwa Dep.- 5.20 pm, Nabadwip Arr. – 6.05 pm,: "
*/

