var routes4 = [ 

"Taraknath Nabadwip to Asansol 0035: Nabadwip to Asansol [ via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Durgapur City Centre, Andal, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep.  – 4.20 am, Satgachia Dep. – 5.40 am, Barddhaman Dep. – 6.55 am, Durgapur City Center Dep. – 8.20 am, Asansol Arr. – 9.20 am,: xyz.jpg",
"Taraknath Nabadwip to Asansol 0035: Asansol To Nabadwip [ via: Asansol, Kalipahari More, Raniganj Punjabi More, Andal, Durgapur City Centre, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 10.00 am, Durgapur City Center Dep. – 11.10 pm, Barddhaman Dep. – 1.10 pm, Satgachia Dep. – 2.40 pm, Nabadwip Arr. – 3.45 pm,: ",

"Sweety Nabadwip to Asansol 1460: Nabadwip to Asansol [ via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Durgapur City Centre, Andal, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep.  – 5.05 am, Dhatrigram Dep. – 5.50 am Satgachia Dep. – 6.20 am, Barddhaman Dep. – 7.25 am, Panagarh Dep. – 8.15 am, Durgapur City Center Dep. – 8.50 am, Asansol Arr. – 9.50 am,: xyz.jpg",
"Sweety Nabadwip to Asansol 1460: Asansol To Nabadwip [ via: Asansol, Kalipahari More, Raniganj Punjabi More, Andal, Durgapur City Centre, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 11.40 am, Durgapur City Center Dep. – 1.00 pm, Panagarh Dep. – 1.30 pm, Barddhaman Dep. – 2.40 pm, Satgachia Dep. – 4.00 pm, Dhatrigram Dep. – 4.35 pm, Nabadwip Arr. – 5.15 pm,: ",

"Sweety Nabadwip to Asansol 9888: Nabadwip to Asansol [ via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Durgapur City Centre, Andal, Raniganj Punjabi More, Kalipahari More, Asansol] : Nabadwip Dep. – 5.40 am, Satgachia Dep.  – 7.05 am, Barddhaman Dep. – 8.30 am, Durgapur City Center Dep. – 10.00 am, Asansol Arr. – 11.00 am,: xyz.jpg",
"Sweety Nabadwip to Asansol 9888: Asansol To Nabadwip [ via: Asansol, Kalipahari More, Raniganj Punjabi More, Andal, Durgapur City Centre, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip] : Asansol Dep. – 1.20 pm, Durgapur City Center Dep. – 2.25 pm, Barddhaman Dep. – 4.20 pm, Satgachia Dep. – 5.30 pm, Nabadwip Arr. – 6.50 pm,: ",

"Chaitanya Nabadwip to Asansol 9662: Nabadwip to Asansol [ via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Durgapur City Centre, Andal, Raniganj Punjabi More, Kalipahari More, Asansol ] : Nabadwip Dep. – 4.00 am, Kusumgram Dep. – 5.20 am, Barddhaman Dep. – 6.30 am, Panagarh Dep. – 7.30 am, Durgapur City Center Dep. – 7.55 am, Asansol Arr. – 9.00 am,: xyz.jpg",
"Chaitanya Nabadwip to Asansol 9662: Asansol To Nabadwip [ via: Asansol, Kalipahari More , Raniganj Punjabi More, Andal, Durgapur City Centre, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip ] : Asansol Dep. – 11.00 am, Durgapur City Center Dep. – 12.10 pm, Panagarh Dep. – 12.40 pm, Barddhaman Dep. – 2.15 pm, Kusumgram Dep. – 3.35 pm, Nabadwip Arr. – 4.30 pm,: ",

"Sweety Nabadwip to Asansol 5929: Nabadwip to Asansol [ via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Durgapur City Centre, Andal, Raniganj Punjabi More, Kalipahari More, Asansol ] : Nabadwip Dep. – 4.40 am, Kusumgram Dep. – 5.35 am, Barddhaman Dep. – 6.45 am, Budbud Dep. – 7.25 am, Panagarh Dep. – 7.40 am, Durgapur City Center Dep. – 8.10 am, Asansol Arr. – 9.10 am,: xyz.jpg",
"Sweety Nabadwip to Asansol 5929: Asansol To Nabadwip [ via: Asansol, Kalipahari More , Raniganj Punjabi More, Andal, Durgapur City Centre, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip ] : Asansol Dep. – 9.50 am, Durgapur City Center Dep. – 10.50 am, Panagarh Dep. – 11.20 am, Budbud Dep. – 11.40 am, Barddhaman Dep. – 12.40 pm, Kusumgram Dep. – 2.00 pm, Nabadwip Arr. – 2.50 pm,: ",

"Ravi Nabadwip to Asansol 5161: Nabadwip to Asansol [ via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Durgapur City Centre, Andal, Raniganj Punjabi More, Kalipahari More, Asansol ] : Nabadwip Dep. – 5.15 am, Kusumgram Dep. – 6.25 am, Barddhaman Dep. – 7.55 am, Panagarh Dep. – 8.50 am, Durgapur City Center Dep. – 9.20 am, Asansol Arr. – 10.20 am,: xyz.jpg",
"Ravi Nabadwip to Asansol 5161: Asansol To Nabadwip [ via: Asansol, Kalipahari More , Raniganj Punjabi More, Andal, Durgapur City Centre, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip ] : Asansol Dep. – 12.30 pm, Durgapur City Center Dep. – 1.35 pm, Panagarh Dep. – 2.00 pm, Barddhaman Dep. – 3.40 pm, Kusumgram Dep. – 5.15 pm, Nabadwip Arr. – 6.15 pm,: ",

"Krishna Nabadwip to Asansol 4681: Asansol To Nabadwip [ via: Asansol, Kalipahari More , Raniganj Punjabi More, Andal, Durgapur City Centre, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman Station, Dewandighi More, Kurmun, Bhandardihi, Malamba, Kusumgram, Raigram, Nadanghat, Rajibpur, Nadanghat More, Hematpur More, Nabadwip ] : Asansol Dep. – 6.30 am, Durgapur City Center Dep. – 7.30 am, Panagarh Dep. – 8.00 am, Barddhaman Arr. – 9.00 am, Barddhaman Dep. – 9.30 am, Kusumgram Dep. – 10.50 am, Nabadwip Arr. – 11.40 am,: xyz.jpg",
"Krishna Nabadwip to Asansol 4681: Nabadwip to Asansol [ via: Nabadwip, Hematpur More, Nadanghat More, Rajibpur, Nadanghat, Raigram, Kusumgram, Malamba, Bhandardihi, Kurmun, Dewandighi More, Barddhaman Station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Durgapur City Centre, Andal, Raniganj Punjabi More, Kalipahari More, Asansol ] : Nabadwip Dep. – 12.25 pm, Kusumgram Dep. – 1.35 pm, Barddhaman Dep. – 3.10 pm, Panagarh Dep. – 4.00 pm Durgapur City Center Dep. – 4.25 pm, Asansol Arr. – 5.30 pm,: ",

"Sweety Nabadwip to Bankura 4545: Nabadwip to Bankura [ via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur Station, Borjora, Beliatore, Bankura ] : Nabadwip Dep.  – 2.55 am, Dhatrigram Dep. – 3.30 am Satgachia Dep.  – 4.05 am, Barddhaman Dep. – 5.20 am, Durgapur Station Dep. – 6.55 am,: xyz.jpg",
"Sweety Nabadwip to Bankura 4545: Bankura To Nabadwip [via: Bankura, Beliatore , Borjora, Durgapur Station, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip ] : Bankura Dep. – 9.50 am, Durgapur Station Dep. – 11.30 am, Barddhaman Dep. – 1.45 pm, Satgachia Dep. – 2.50 pm, Dhatrigram Dep. – 3.20 pm,: ", 

"Sweety Nabadwip to Bankura 9311: Nabadwip to Bankura [ via: Nabadwip, Hematpur More, Nadanghat More, Samudragarh, Dhatrigram, Madhupur, Bulbulitala, Bohar, Satgachia, Paharhati, Nabastha, Hatgobindopur, Barddhaman station, Golapbag, Barddhaman Nawabhat Bus Stand, Galsi, Budbud, Panagarh, Muchipara, Durgapur Station, Borjora, Beliatore, Bankura ] : Nabadwip Dep. 3.50 am, Barddhaman Dep. – 6.25 am Muchipara Dep. – 47.45 am, Durgapur Station Dep. – 8.10 am, Bankura Arr. – 9.30 am,: ",
"Sweety Nabadwip to Bankura 9311: Bankura To Nabadwip [ via: Bankura, Beliatore , Borjora, Durgapur Station, Muchipara, Panagarh, Budbud, Galsi, Barddhaman Nawabhat Bus Stand, Golapbag, Barddhaman station, Hatgobindopur, Nabastha, Paharhati, Satgachia, Bohar, Bulbulitala, Madhupur, Dhatrigram, Samudragarh, Nadanghat More, Hematpur More, Nabadwip ] : Bankura Dep. – 10.55 am, Durgapur Station Dep. – 12.20 am, Muchipara Dep. – 12.40 pm,  Barddhaman Dep. – 2.20 pm, Nabadwip Arr. – 4.50 pm : xyz.jpg"

];
